### ISSUE TITLE
Change or remove the Matrix feed at the bottom of the forum footer

### ISSUE THREAD

**Issue by 8pen-s8urce** [techlore/discourse-techlore#6]
The Matrix feed linked in the forum footer directs to a page saying:
"The Matrix Public Archive has been discontinued".

The previously mentioned Matrix feed: https://archive.matrix.org/r/techlore-discussions:matrix.org

Considering this, should the link be changed to the current Matrix feed or should the mention to the Matrix feed in the forum footer be fully removed?

The updated Matrix feed: https://matrix.to/#/%23techlore:matrix.org

Also, why is the Matrix feed even showcased in the footer? Did it used to be a feed with original content or something equally important, different from the current Matrix feed?

**Comment by henry-fisher** [comment]
https://github.com/techlore/discourse-techlore/commit/c714be207b1e6be7834173c85629511719e85fee

Just fixed this! Sorry for the delay on it. It'll be live on the forum soon.
